from __future__ import annotations

from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parents[1] / "include" / "weights_current.hpp"


def float_literal(value: np.float32) -> str:
    return f"{float(value):.9g}f"


def write_array(lines: list[str], name: str, array: np.ndarray) -> None:
    flat = array.astype(np.float32, copy=False).reshape(-1)
    lines.append(f"inline constexpr float {name}[{flat.size}] = {{")
    chunk = []
    for index, value in enumerate(flat, 1):
        chunk.append(float_literal(value))
        if len(chunk) == 8 or index == flat.size:
            lines.append("    " + ", ".join(chunk) + ("," if index != flat.size else ""))
            chunk = []
    lines.append("};")
    lines.append("")


def main() -> None:
    weights_path = ROOT / "numpy_network_weights.npz"
    wb = np.load(weights_path, allow_pickle=True)["wb"]
    weights, biases = wb
    w0, w1 = weights
    b0, b1 = biases
    if w0.shape != (66, 44) or w1.shape != (44, 1) or b0.shape != (44,) or b1.shape != (1,):
        raise ValueError(f"unexpected active weight shapes: {w0.shape}, {w1.shape}, {b0.shape}, {b1.shape}")

    lines = [
        "#pragma once",
        "",
        "// Generated by cpp_minizero/tools/export_weights.py from numpy_network_weights.npz.",
        "namespace minizero_weights {",
        "inline constexpr int INPUT_SIZE = 66;",
        "inline constexpr int HIDDEN_SIZE = 44;",
        "",
    ]
    write_array(lines, "W0", w0)
    write_array(lines, "B0", b0)
    write_array(lines, "W1", w1.reshape(44))
    write_array(lines, "B1", b1)
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
